# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Zahra Hosseini
title:
email: hosseini99.zahra@gmail.com


# Social links
#twitter_username: chiiivirus
github_username:  zahrahosseini99
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: arhaz.exe
linkedin_username: zahra-hosseini-174663174
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/mypro.png
about_content: | # this will include new lines to allow paragraphs
I am currently studying the final year of my bachelor’s degree in Computer Engineering.

#Projects Section
projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:
   - Rock Music
   - Karate Shotokan WSKF
   - Basketball
   - Reading about Technology , Cosmology , Physics and Astronomy
   - Digital painting, Pencil painting


# Footer
footer_show_references: true

# Build settings
remote_theme: zahrahosseini99/zahrahosseini99.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
